### ISSUE TITLE
docker部署完毕，测试返回消息403

### ISSUE THREAD

**Issue by altmanrobots** [xiaozhou26/deeplx-pro#18]
![image](https://github.com/user-attachments/assets/91654f3d-499b-4cbb-be84-a28339ae517c)
现在获取的dl_session 前面多了一个 fa. 我看代码校验了长度，如果加fa. 就无法通过，不加的话目前就抛出403了{"details":"error: 403","error":"Translation failed"}

**Comment by xiaozhou26** [comment]
fa是普通用户
