### ISSUE TITLE
500: {"details":"no valid cookies available","error":"Translation failed"}

### ISSUE THREAD

**Issue by Fan-Bob** [xiaozhou26/deeplx-pro#8]
500: {"details":"no valid cookies available","error":"Translation failed"}

**Comment by Fan-Bob** [comment]
Vercel部署，我确定cookies没有问题

**Comment by xiaozhou26** [comment]
vercel默认区域的ip已经被薅风控了

**Comment by Fan-Bob** [comment]
我换rn的ip了，现在的报错是
测试失败
Failed to fetch

**Comment by Fan-Bob** [comment]
Welcome to deeplx-pro
打开网页是有这句话的，但是都是调用一两次，后续就需要不停的重试

**Comment by xiaozhou26** [comment]
> Welcome to deeplx-pro 打开网页是有这句话的，但是都是调用一两次，后续就需要不停的重试

那就是ip问题，nodejs环境我没有补齐，你试一下go的https://github.com/xiaozhou26/deeplx-pro-go

**Comment by xiaozhou26** [comment]
> 我换rn的ip了，现在的报错是 测试失败 Failed to fetch

一开始可以调用成功？

**Comment by yidasanqian** [comment]
碰到同样问题，直接访问是Welcome to deeplx-pro，调用接口就报错
