### ISSUE TITLE
有问题，可以试一下go版本https://github.com/xiaozhou26/deeplx-pro-go

### ISSUE THREAD

**Issue by xiaozhou26** [xiaozhou26/deeplx-pro#9]
https://github.com/xiaozhou26/deeplx-pro-go

**Comment by Fan-Bob** [comment]
503: {"code":503,"message":"Translation failed, API returns an empty result."}
Go版本可以翻译挺多，但是后续会一直给这个报错

**Comment by xiaozhou26** [comment]
> 503: {"code":503,"message":"Translation failed, API returns an empty result."} Go版本可以翻译挺多，但是后续会一直给这个报错

返回为空，大概率是你翻译的东西有特殊符号，我当时就遇到这个错误才加的
